### ISSUE TITLE
FATFS_VFS.h not found?

### ISSUE THREAD

**Issue by PRO2XY** [nkolban/ESP32_Explorer#1]
I am unable to compile the ESP32_Explorer source using Eclipse (and also using make directly from mingw32) as recommended in the ESP-IDF "Getting Started" guide. 

The error I receive is related to FATFS_VFS.h not being found. 
`ESP32_Explorer/main/main.cpp:4:23: fatal error: FATFS_VFS.h: No such file or directory` 
`compilation terminated.`

I have found the FATFS_VFS.h and .cpp in the "esp32_snippets" repository [here](https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/FATFS_VFS.h) and [here](https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/FATFS_VFS.cpp), and copied them to the project folder at the following location, but neither of these could help me get rid of the error. 

FATFS_VFS.h and FATFS_VFS.cpp copied to (one location at a time):
- ESP32_Explorer/
- ESP32_Explorer/main
- ESP32_Explorer/src
- ESP32_Explorer/main/src

Where are these files supposed to be located for the compiler to 'see' them?

**Comment by Ebiroll** [comment]
I compiled the project. This is how I located the files:
https://github.com/Ebiroll/qemu_esp32/tree/master/examples/24_esp32_explorer
I tried to upload files to the FAT filesystem like this, but was not so successful.

> atftp -p -l index.html -r /index.html 192.168.1.99 69

**Comment by nkolban** [comment]
Oooh ... I see what's happening.  To be honest, I'm using this repository as a location for this project which is still being loosely baked.  There is still much more to be done on this project before it is ready for prime time.

However, should one wish to continue tinkering with it, it has a pre-req of the source code of the "cpp_utils" source tree found here:

https://github.com/nkolban/esp32-snippets/tree/master/cpp_utils

This is where FATFS_VFS_xxx will be found.

**Comment by PRO2XY** [comment]
Hey! I'm so sorry I never got back to this issue. IIRC, I was able to locate the files, but the project didn't compile. It's been a long time now, so I don't recall the result that well anymore. 
Anyhow, thanks for your help!

**Comment by nkolban** [comment]
No problems.  If it comes up again or you have new problems, just re-open the issue or create a new one.
